from enum import Enum

class ResponseSignal(Enum):
    FILE_VALID = "FILE_VALID"
    FILE_TYPE_NOT_ALLOWED = "FILE_TYPE_NOT_ALLOWED"
    FILE_SIZE_EXCEEDED = "FILE_SIZE_EXCEEDED"
    FILE_SUCCESSFULLY_UPLOADED = "FILE_SUCCESSFULLY_UPLOADED"
    FILE_FAILED_TO_UPLOAD = "FILE_FAILED_TO_UPLOAD"
